# Generated by Django 2.2.6 on 2019-10-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
