# Generated by Django 2.2.6 on 2019-10-29 22:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('REST', '0005_album_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='author',
            new_name='author_name',
        ),
    ]
